### ISSUE TITLE
SSL certificate expired on forums.servicestack.net

### ISSUE THREAD

**Issue by UriHendler** [ServiceStack/Issues#441] opened 2016-06-06 07:55 UTC

**Comment by Layoric** [comment] 2016-06-06 08:05
We renewed the forums SSL certificate recently and I can't reproduce the issue.

Could you let me know what device and browser you are using? We are using LetsEncrypt to generate SSL certificate so might be an issue with an intermediate certificate, but would need to know more.

**Comment by UriHendler** [comment] 2016-06-06 08:57
This is strange...

In Chrome 50 and IE 10, it's loading the page with an old certificate:

Thumbprint: ‎bb 17 27 f5 14 fa 17 44 40 19 59 41 e5 ac 4e ab 05 70 11 b0
Issued by: ESET SSL Filter CA
Valid From: ‎06 ‎March ‎2016 07:51:00 AM
Valid To: ‎04 ‎June ‎2016 07:51:00 AM

In Pale Moon (Firefox fork) it's loading the page with the new Let's Encrypt certificate.

I'm going to restart and see if that helps.

**Comment by Layoric** [comment] 2016-06-06 11:55
@UriHendler Yeah that is strange. I have Chrome 50+ IE 11 on Win 8 and Win 7 and both are fine. 

The Certificate you've specified looks like the one we renewed from. 

Let us know if the reboot fixes the issue.

**Comment by Layoric** [comment] 2016-06-08 23:58
Closing issue, as I'd say this is an intermediate certificate issue. Reopen if you are still having issues after your reboot/update.

**Closed by Layoric** 2016-06-08 23:58 UTC
