### ISSUE TITLE
UseParameterizeSqlExpressions BUG in ORMLITE

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#392] opened 2016-01-18 03:56 UTC
this is throw ex
the ex:You must declare the scalar variable "@0"。
![0v5h z_c qumuizcr ct j](https://cloud.githubusercontent.com/assets/1761858/12382975/47e02ec4-bddb-11e5-98f3-bbfa4c971c32.png)

**Comment by mythz** [comment] 2016-01-18 05:25
I can't tell what the issue is with that screenshot, can you please provide a complete example I can run that fails?

**Comment by mythz** [comment] 2016-01-18 05:49
Nevermind I believe found the issue. Should be fixed from this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/9fc667b4560b92209cb732c0d78f56553c5ddfbc

This change is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Closed by mythz** 2016-01-18 05:49 UTC

**Comment by hgp7369** [comment] 2016-01-18 14:00
great！！I express too simple，it's my mistake
