### ISSUE TITLE
Swagger UI does not load after upgrade to 4.0.40

### ISSUE THREAD

**Issue by shuvabrata** [ServiceStack/Issues#287] opened 2015-05-25 05:48 UTC
Hi,
I am using my Visual Studio 2013. Using the nu-get package manager I upgraded all ServiceStack packages to version 4.0.40. After upgrade, my Swagger UI pages says 

"Can't read swagger JSON from https://localhost:9443/api/v1/swagger-ui/resources"

https://localhost:9443/api/v1/metadata is loading just fine, but not when you click on "Swagger-UI". I dont know how to debug this issue. Help needed.

I was previously using version 4.0.38 and everything was working fine.

**Comment by mythz** [comment] 2015-05-25 13:12
Can you post the raw HTTP Response Headers for the Swagger url:

    https://localhost:9443/api/v1/swagger-ui/resources

You can get the raw HTTP Headers using something like Chrome WebInspector or Fiddler.

**Comment by mythz** [comment] 2015-05-25 13:17
Can you also provide your Web.Config ServiceStack Handler Config and any custom `HostConfig` in your AppHost.

**Comment by shuvabrata** [comment] 2015-05-25 13:59
From Chrome Advanced Rest Client, its a 404. See attached image:
![swagger](https://cloud.githubusercontent.com/assets/6500909/7798186/4a0cb32a-0314-11e5-8593-17cb3ae558b9.jpg)

**Comment by shuvabrata** [comment] 2015-05-25 14:05
As far as config is concerned, my app.config has only the ServiceStack License key, log4net config. Rest all all my application specific settings. Mine is a Console Application.

My Apphost.cs is quite long. All config related code is pasted selectively below:

LogManager.LogFactory = new Log4NetFactory(configureLog4Net: true);


----------------------------


//Setup Request filter.
            this.GlobalRequestFilters.Add((request, response, requestDto) =>
            {
                LogIncomingRequest(request, response, requestDto);
            });

            //Setup response filter.
            this.GlobalResponseFilters.Add((request, response, responseDto) =>
            {
                LogOutgoingResponse(request, response, responseDto);
            });

---------------------

AuthFeature authFeature = new AuthFeature(() => new AuthUserSession(),
                                new IAuthProvider[] {
                                new xxxxBasicAuthProvider(), 
                                new xxxxCredentialsAuthProvider() //HTML Form post of User/Pass                              
                                //new CredentialsAuthProvider()
                                }
                        ) { HtmlRedirect = null };

            Plugins.Add(authFeature);


------------------------------


Plugins.Add(new RegistrationFeature());


--------------------------------



container.Register<ICacheClient>(new MemoryCacheClient());


-----------------------------------

SetConfig(new HostConfig { DebugMode = true });

Plugins.Add(new ValidationFeature());

container.RegisterValidators(typeof(Machines).Assembly);

Plugins.Add(new RequestLogsFeature());

Plugins.Add(new SwaggerFeature());

**Comment by mythz** [comment] 2015-05-25 15:51
The issue is that it shouldn't include `/swagger-ui` in the Swagger resources url, so the correct url for you might be:

    https://localhost:9443/api/v1/resources

But I want to know at which path you have ServiceStack hosted at so I'd like to see the ServiceStack Handler mapping path in the Web.config, which should be under either:

```xml
<system.web>
  <httpHandlers> 
    <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*"/>
  </httpHandlers> 
<system.web>
```

or 

```xml
<system.webServer>
  <handlers>
    <add path="*" name="ServiceStack.Factory" preCondition="integratedMode" ...
  </handlers>
</system.webServer>
```

**Comment by shuvabrata** [comment] 2015-05-25 16:44
You are right, putting in "https://localhost:9443/api/v1/resources" manually in the Swagger text box works. So now I need to find out what is causing it to add /swagger-ui/ after the upgrade. 

As for the .config file, I dont have any. My project is derived from AppSelfHostBase 

public class AppHost : AppSelfHostBase
    {
        private ILog log = null;
        /// <summary>
        /// Default constructor.
        /// Base constructor requires a name and assembly to locate web service classes. 
        /// </summary>
        public AppHost()
            : base("ServiceStackSelfHost1", typeof(MyServices).Assembly)
        {

        }


The EXE produced is ApiServer.exe. I just have the ApiServer.exe.config and I just have the license and log4net setting in there.

Is there any config changes I should make.

**Comment by mythz** [comment] 2015-05-25 16:45
Please provide the Web.config ServiceStack handler mapping as requested in the previous comments.

**Comment by mythz** [comment] 2015-05-25 16:48
Please provide the url you're starting the ServiceStack AppHost at.

**Comment by shuvabrata** [comment] 2015-05-26 06:01
Its 

https://*:9443/api/v1/

In browser when I open: https://localhost:9443/api/v1/ it becomes

https://localhost:9443/api/v1/metadata

and it shows a lot of information correctly, including a section named "Plugin Links" which contains "Swgger UI" (https://localhost:9443/api/v1/swagger-ui/).

I am going to try to create a fresh Visual Studio project with barebones and see if I can reproduce. if yes, I will upload the entire Solution here.

**Comment by shuvabrata** [comment] 2015-05-26 06:50
I have managed to reproduce this with bare minimum config.I have the entire Visual Studio solution that I can share. Its a 6KB zip file. How can I upload or share this with you?

**Comment by mythz** [comment] 2015-05-26 07:44
Can you just add it to a new GitHub repo and send me the link?

**Comment by shuvabrata** [comment] 2015-05-26 12:30
Here it is:
https://github.com/shuvabrata/ServiceStackIssue287

**Comment by mythz** [comment] 2015-05-26 17:42
Thanks for the repro it looks like there's an issue inferring the BaseUrl, but as a workaround you can specify the BaseUrl which will be used instead with:

```csharp
SetConfig(new HostConfig {
    DebugMode = true,
    WebHostUrl = "http://localhost:9443/api/v1/"
});
```

In the meantime I'll work on a fix.

**Comment by mythz** [comment] 2015-05-26 18:56
This should now be fixed with this commit: https://github.com/ServiceStack/ServiceStack/commit/f24cda8e4b2c48bce0521737ced7d0d96a29372e

Which will be available in the next release of ServiceStack.

**Closed by mythz** 2015-05-26 18:56 UTC
