### ISSUE TITLE
Redis Timeouts (Issue #592)

### ISSUE THREAD

**Issue by lamnguyen108** [ServiceStack/Issues#595] opened 2018-01-30 18:42 UTC
Hello,

I'd like to re-open this Redis timeout issue that was closed (#592). We're continuing to see the error 
 (Timeout Error) below in every environment that we've deployed Redis to. Concurrently, we're seeing a message in the Redis logs about an existing connection being forcibly closed (Redis Log). The errors seem to be occurring too frequently to be just network errors, and the servers aren't under much load, at all. Do you have any idea what might be going on, and how we can get rid of these errors? Are we somehow using the ServiceStack library incorrectly? We're keeping a single IRedisClientsManager around in a singleton class, and using it to create clients as needed, like so:

```
ClientDispatcher() {
_sentinel = new RedisSentinel(sentinelHosts, Config.ServiceName)
            {
                HostFilter = HostFilter,
                RedisManagerFactory = (master, slaves) => new RedisManagerPool(master)
            };
_clientsManager = _sentinel.Start();
}
...


using (var client = _clientsManager.GetClient())
            {
                action(client);
            }

```
Thanks,
Lam

Timeout Error:

["2018-01-30T09:48:40.617","ERROR","ESD1APOLYNGTT42","ServiceStack.Redis.RedisNativeClient",["SocketException in SendReceive, retrying..."
,"System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"
,"   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)"],{},{}]
["2018-01-30T09:48:40.617","ERROR","ESD1APOLYNGTT42","ServiceStack.Redis.RedisNativeClient",["Exceeded timeout of 00:00:10"],{},{}]
["2018-01-30T09:48:40.617","ERROR","ESD1APOLYNGTT42","ServiceStack.Redis.RedisSentinel",["Could not get active Sentinels from: 10.12.7.235:26379"
,"ServiceStack.Redis.RedisException: Exceeded timeout of 00:00:10 ---> ServiceStack.Redis.RedisRetryableException: Socket is not connected"

Redis Log:

[1732] 30 Jan 09:29:39.928 - Reading from client: An established connection was aborted by the software in your host machine.
[1732] 30 Jan 09:29:50.920 - Accepted 10.12.7.235:61467
[1732] 30 Jan 09:29:50.920 - Reading from client: An existing connection was forcibly closed by the remote host.

**Comment by mythz** [comment] 2018-01-30 19:24
This Exception is from .NET's Socket implementation where it is unable to establish a TCP connection to the remote Redis instance. i.e. .NET's low-level API to create a TCP Network connection, there's nothing else the ServiceStack.Redis library can do but to retry to connect up to the configured `RedisConfig.DefaultRetryTimeout` as mentioned in the previous answer. 

If you're also seeing the TCP connection failed in Redis Logs that means the TCP connection can't maintain a persistent network connection, when the client TCP Connection fails ServiceStack.Redis tries to auto-reconnect which it's been unable to do within the configured Retry Timeout. There's nothing else the client is going to be able to do as it fundamentally needs to establish a TCP connection in order to communicate with the Redis instance.

The first thing you can look at doing is try localizing the source of the issue, i.e. when these errors occur [try to connect to the Redis instance using Redis's `redis-cli`](https://redislabs.com/redis-enterprise-documentation/administering/troubleshooting/testing-client-connectivity/), first from the remote Server where you're using the Redis Client from. 

If you're **not able** to connect to the Redis instance, try to connect from the server that's running the Redis server instance. If you're still unable to connect then the issue is with the Redis server instance, if you are able to connect locally then the issue is with the network.

If you **are able** to connect to the remote Redis instance using Redis's `redis-cli` tool try to connect to the Redis instance with the .NET Client:

```csharp
try
{
    using (var redis = new RedisClient(connectionString))
    {
        var connected = redis.Ping();
    }
} 
catch (Exception ex) 
{
    //connection failed
}
```

If this does work then it suggests that the network condition was temporary in which case increasing the configured `RedisConfig.DefaultRetryTimeout` should reduce the frequency of the errors.

If it doesn't work with the .NET Client above, but it does work with `redis-cli` from the same machine then I can only assume that something like a local AV/Firewall is interfering with the .NET program, but I've never seen this in practice.

Please report your findings, I'm going to close this issue as there's noting actionable we can do in ServiceStack.Redis to mitigate this issue beyond increasing the `RedisConfig.DefaultRetryTimeout`.

**Closed by mythz** 2018-01-30 19:24 UTC

**Comment by lamnguyen108** [comment] 2018-01-31 22:30
Some more details upon further investigation, and carrying out the steps you suggested:

I lengthened the DefaultRetryTimeout to 3 minutes, which exposed that there's definitely something going wrong. Sometimes things will work perfectly, but when the timeout problems start happening, no requests will be able to be served even if we open a brand new browser, until the 3 minutes are up. Is this because the client manager is stuck trying to make that one initial connection?

I'm able to connect to all of the sentinel servers and the master with redis-cli. I'm also able to run the ping program you suggested building from the server that's having trouble making the redis connection. 

Again, the error being logged is:

> "ServiceStack.Redis.RedisSentinel",["Could not get active Sentinels from: 10.12.7.195:26379"

When I look at the sentinel.log created by Redis, I'm seeing connections seemingly being established and closed over and over again while the request waits:

> [2024] 31 Jan 13:54:42.451 - Accepted 10.12.7.195:62114
> [2024] 31 Jan 13:54:43.062 - Client closed connection
> [2024] 31 Jan 13:54:43.939 - Accepted 10.12.7.195:62115
> [2024] 31 Jan 13:54:44.553 - Client closed connection
> [2024] 31 Jan 13:54:45.398 - Accepted 10.12.7.195:62116
> [2024] 31 Jan 13:54:46.010 - Client closed connection
> [2024] 31 Jan 13:54:46.876 - Accepted 10.12.7.195:62117
> [2024] 31 Jan 13:54:47.489 - Client closed connection
> [2024] 31 Jan 13:54:48.398 - Accepted 10.12.7.195:62118
> [2024] 31 Jan 13:54:49.010 - Client closed connection
> [2024] 31 Jan 13:54:49.923 - Accepted 10.12.7.195:62119
> [2024] 31 Jan 13:54:50.534 - Client closed connection
> [2024] 31 Jan 13:54:51.416 - Accepted 10.12.7.195:62120

The timeouts seem to be triggered after leaving the application idle for a while, but I haven't quantified this.

Before, I was leaving the DefaultRetryTimeout at 10 seconds and using Polly to retry the ServiceStack.Redis operation up to 3 times, and the errors never bubbled up to the application, but the timeouts generated by the ServiceStack.Redis library were still happening in the logs.

Any idea what might be going on? I'm at my wits end trying to figure this out. This is a WCF service built on .NET 4.5 that's using the ServiceStack.Redis library, by the way, if that makes a difference.

**Comment by mythz** [comment] 2018-01-31 22:58
Did you connect to the RedisSentinel instance on `10.12.7.195:26379` with redis-cli? and were you able to connect with the .NET Ping Console App?

Have the IP and ports of your Redis Sentinel Instances changed from their original IP/port? Has the master changed, i.e. has one of the slaves been promoted to master?

**Comment by lamnguyen108** [comment] 2018-01-31 23:06
Yes, I was able to connect to that particular sentinel with redis-cli. I was also able to connect with the console app from the server trying to make the redis connection.

I'm testing against a brand new redis deployment with all of the sentinels running on the default 26379 port. The master hasn't changed according to any of the logs...

**Comment by mythz** [comment] 2018-01-31 23:09
ServiceStack.Redis failed to connect to `10.12.7.195:26379` but a .NET Console App was able to? ok that's weird. Do you have the full Exception StackTrace for this error?

**Comment by lamnguyen108** [comment] 2018-01-31 23:20
Only the message is being logged, right now, not the full stack trace. I'll work on getting that if it might help.

**Comment by lamnguyen108** [comment] 2018-02-01 17:12
This is the stack trace. Any clues there?

ServiceStack.Redis.RedisRetryableException: Socket is not connected"
,"   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)"
,"   --- End of inner exception stack trace ---"
,"   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)"
,"   at ServiceStack.Redis.RedisNativeClient.SendExpectComplexResponse(Byte[][] cmdWithBinaryArgs)"
,"   at ServiceStack.Redis.RedisNativeClient.SendExpectStringDictionaryList(Byte[][] cmdWithBinaryArgs)"
,"   at ServiceStack.Redis.RedisSentinel.GetActiveSentinelHosts(IEnumerable`1 sentinelHosts)"],{},{}]

**Comment by lamnguyen108** [comment] 2018-02-01 17:32
Also, this appears to happen even when all the sentinels and cache services are running on the same machine. Messages also get logged at odd times of the day sometimes, like late at night when I assume no one is using the system. Could some of these timeout messages be the result of the redis services talking to one another about the state of the cache, and not initiated by user actions?

**Comment by mythz** [comment] 2018-02-01 18:11
This particular StackTrace is happening when the `RedisSentinel` periodically refreshes its cached list of sentinels. So the communication issue in this case is with the sentinel instance (i.e. not the redis instance).

If your Sentinel Hosts are static you can avoid these periodic scans by specifying your different Redis Sentinel hosts in the constructor and setting `ScanForOtherSentinels=false`, e.g:

```csharp
var sentinel1 = new RedisSentinel(new []{"host1:26379","host2:26379","host3:26379"})
{
    ScanForOtherSentinels = false
};
```

If your Sentinel hosts have changed, you can force a manual refresh at runtime with:

```csharp
sentinel.RefreshActiveSentinels();
```

**Comment by lamnguyen108** [comment] 2018-02-02 19:23
Thanks, that's helpful. Is it likely a problem with how our sentinels are configured, then? This happens even in environments where the sentinels are all on one server.

**Comment by mythz** [comment] 2018-02-02 19:30
Can only tell that there's an issue with connecting with the Redis Sentinel instances. If you can repro the issue when running an App on the same server with all the sentinels (i.e. so no Network is involved), then it could be a configuration issue or something interfering with the sentinel processes. If it only happens over the network, it could be networking/firewall related.
