### ISSUE TITLE
Ioc Bug with TryResolve and ReuseScope.Request

### ISSUE THREAD

**Issue by kharabasz** [ServiceStack/Issues#356] opened 2015-09-25 11:15 UTC
I have what I think is a bug in how the IoC container resolves dependencies. Specifically, when you register a dependency with ReuseScope.Request, using TryResolve outside the request processing loop causes resolutions within requests to ignore the ReuseScope.

I have reproduced this behavior with an example self hosting service - you can find the code in this git repository: https://github.com/kharabasz/ServiceStackTryResolveIocBug

Recreating the scenario requires commenting/uncommenting the following line:

    if (container.TryResolve<IDependency>() != default(IDependency))
    {
    }

When commented, behavior is as expected, and a new instance is resolved per request:
ServiceStack SelfHost listening at http://localhost:8088
Filter received: 39570857-82f8-4fd3-b995-0ced22ae3792
Filter received: de6b8a63-057b-49bd-b53e-a04d088f3c26
Filter received: cacae1ad-d699-4b66-8afd-87e437c08412
Filter received: 100805e5-7dbe-45a1-b07a-91a6240d3e93

When uncommented, only once instance is ever resolved:
ServiceStack SelfHost listening at http://localhost:8088
Filter received: b586edfc-6be8-497e-9616-430c79d41be3
Filter received: b586edfc-6be8-497e-9616-430c79d41be3
Filter received: b586edfc-6be8-497e-9616-430c79d41be3
Filter received: b586edfc-6be8-497e-9616-430c79d41be3

This behavior stays the same when SomeDependency is marked iDisposable
ServiceStack SelfHost listening at http://localhost:8088
Disposing: 2c8c0c43-26d4-4b6f-a4e2-d8e883176354
Disposing: 2c8c0c43-26d4-4b6f-a4e2-d8e883176354
Filter received: 2c8c0c43-26d4-4b6f-a4e2-d8e883176354
Disposing: 2c8c0c43-26d4-4b6f-a4e2-d8e883176354
Filter received: 2c8c0c43-26d4-4b6f-a4e2-d8e883176354
Disposing: 2c8c0c43-26d4-4b6f-a4e2-d8e883176354

**Comment by mythz** [comment] 2015-09-26 00:46
The issue is when initializing and populating the CallContext on the main thread will initalize the Request Worker Thread with a copy of the data on each request's CallContext. 

So the CallContext is no longer used when resolving Request Scoped dependencies on Startup in this commit: https://github.com/ServiceStack/ServiceStack/commit/55e33c0c5e2a1125b7e60c0d7d7ae2ec154cd626

This change is available from v4.0.47 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Closed by mythz** 2015-09-26 00:46 UTC
