### ISSUE TITLE
JsvServiceClient throws ArgumentException in Xamarin

### ISSUE THREAD

**Issue by thomfre** [ServiceStack/Issues#520] opened 2017-02-22 14:10 UTC
When using JsvServiceClient in Xamarin Android, we get the following exception when doing a get:
```csharp
System.ArgumentException: The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name
  at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader (System.String headerName) [0x00021] in /Users/builder/data/lanes/4009/3d959b66/source/mono/mcs/class/referencesource/System/net/System/Net/WebHeaderCollection.cs:574 
  at System.Net.WebHeaderCollection.Set (System.String name, System.String value) [0x0001f] in /Users/builder/data/lanes/4009/3d959b66/source/mono/mcs/class/referencesource/System/net/System/Net/WebHeaderCollection.cs:705 
  at System.Collections.Specialized.NameValueCollection.set_Item (System.String name, System.String value) [0x00000] in /Users/builder/data/lanes/4009/3d959b66/source/mono/mcs/class/referencesource/System/compmod/system/collections/specialized/namevaluecollection.cs:337 
  at System.Net.WebHeaderCollection.set_Item (System.Net.HttpRequestHeader header, System.String value) [0x0001b] in /Users/builder/data/lanes/4009/3d959b66/source/mono/mcs/class/referencesource/System/net/System/Net/WebHeaderCollection.cs:288 
  at ServiceStack.NetStandardPclExport.Config (System.Net.HttpWebRequest req, System.Nullable`1[T] allowAutoRedirect, System.Nullable`1[T] timeout, System.Nullable`1[T] readWriteTimeout, System.String userAgent, System.Nullable`1[T] preAuthenticate) [0x0000a] in <3a9115e15bc9432a81ee49f65fe0d753>:0 
  at ServiceStack.ServiceClientBase.PrepareWebRequest (System.String httpMethod, System.String requestUri, System.Object request, System.Action`1[T] sendRequestAction) [0x000af] in <d8daa4e0b67847028f6078aec4af0c3f>:0 
  at ServiceStack.ServiceClientBase.SendRequest (System.String httpMethod, System.String requestUri, System.Object request) [0x00014] in <d8daa4e0b67847028f6078aec4af0c3f>:0 
  at ServiceStack.ServiceClientBase.Send[TResponse] (System.String httpMethod, System.String relativeOrAbsoluteUrl, System.Object request) [0x00067] in <d8daa4e0b67847028f6078aec4af0c3f>:0 
  at ServiceStack.ServiceClientBase.Get[TResponse] (ServiceStack.IReturn`1[T] requestDto) [0x00012] in <d8daa4e0b67847028f6078aec4af0c3f>:0 
```

We tried reproducing this in a smaller project, first in a .NET Core console app, then in a blank Xamarin Android app. We get no exceptions in the console app, but in the Xamarin app we get the same exception as we do in our project app.

The code we tested in Xamarin Android:
```csharp
    public class MainActivity : Activity
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            // Set our view from the "main" layout resource
            // SetContentView (Resource.Layout.Main);


            JsvServiceClient jsvServiceClient = new JsvServiceClient($"https://niceurl/niceservice")
            {
                Credentials = new NetworkCredential("xxx", "xxx")
            };

            SomeResponse someResponse = jsvServiceClient.Get(new SomeRequest());
        }

        [Route("/some")]
        public class SomeRequest : IReturn<SomeResponse>
        {
        }

        public class SomeResponse
        {
            public string Result { get; set; }
        }
    }
```

**Comment by xplicit** [comment] 2017-02-22 14:35
This error means that Xamarin does not support NetStandard 1.3 specification yet. In NetStandard 1.3 there is no property `UserAgent` in `HttpWebRequest` so the only way to set up `User-Agent` header is modifying headers collection, which works fine in .NET Core. So this bug should be filed to Xamarin, they should not throw this exception for NetStandard libraries.

You should use `ServiceStack.Client` PCL version for Xamarin instead of .NET Core client until NetStandard specification will be supported fully by Xamarin.

**Comment by dabide** [comment] 2017-02-22 14:37
Are you sure? https://msdn.microsoft.com/en-us/library/system.net.webheadercollection.aspx says that `User-Agent` is restricted.

**Comment by xplicit** [comment] 2017-02-22 14:42
@dabide it's restricted in .NET, but not in .NET Core. In .NET Core most of these properties are removed from HttpWebRequest.

**Comment by dabide** [comment] 2017-02-22 15:01
Hmm, so that means there must be a bug in Xamarin, because AFAIK they officially support NetStandard 1.3. Thanks!

**Comment by dabide** [comment] 2017-02-22 15:07
@xplicit, BTW, is there a reason for ServiceStack still using `HttpWebRequest` in stead of `HttpClient`? 

> In general, for better app performance and features, we recommend developers move away from HttpWebRequest and adopt HttpClient API surface. https://github.com/dotnet/corefx/issues/7862#issuecomment-211986998

**Comment by mythz** [comment] 2017-02-22 15:23
@dabide It's the original, well supported, faster and allows proper sync requests. If you want to use HttpClient use [JsonHttpClient](http://docs.servicestack.net/csharp-client#jsonhttpclient) from **ServiceStack.HttpClient** instead.

Closing as this should be resolved in Xamarin's libraries.

**Closed by mythz** 2017-02-22 15:23 UTC

**Comment by dabide** [comment] 2017-02-22 16:57
For the record: https://bugzilla.xamarin.com/show_bug.cgi?id=52672

**Comment by dabide** [comment] 2017-02-22 17:01
@mythz, thanks for a thorough reply. The reason for using the .NET Core version in Xamarin was that we have class library projects that are referenced from both our Xamarin Android projects and our .NET Core projects.

**Comment by dabide** [comment] 2017-02-28 16:02
@mythz, according to the Xamarin project, this isn't a bug in their code. The issue was closed:

> This is not Mono/Xamarin bug. NetStandard does not specified the implementation only API contract and in this case Xamarin behaves same as .net (if you run the code on .net you get same exception).

>The best fix is to update to netstandard API which supports UserAgent property

https://bugzilla.xamarin.com/show_bug.cgi?id=52672

**Comment by xplicit** [comment] 2017-03-01 06:15
@dabide `HttpWebRequests.UserAgent` is not a part of current released NetStandard 1.6 and it is not implemented in the latest released .NET Core 1.1 libraries. Possible it will be available under NetStandard 2.0 specification, because latest source of .NET Core code contains implementation of `UserAgent`

https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L256

**Comment by xplicit** [comment] 2017-03-02 01:34
@dabide We made a workaround for this issue, and `ServiceStack.Client.Core 1.0.37` (available on nuget) should work now with Xamarin mono platform.

**Comment by mikkeljohnsen** [comment] 2017-03-15 14:22
It is not working with 1.0.37.

The same error occurs

**Comment by xplicit** [comment] 2017-03-15 15:32
@mikkeljohnsen do you use it with Android or iOS?

**Comment by mikkeljohnsen** [comment] 2017-03-15 15:33
@xplicit I am using iOS and Xamarin.Forms

**Comment by xplicit** [comment] 2017-03-15 15:41
@mikkeljohnsen then you should tell linker to not remove `UserAgent` property. This property is not referenced by compiler (used only via reflection, so iOS linker thinks it about it as unusable and remove it). There are a linker options to tell not to remove the property. See this topic:

https://developer.xamarin.com/guides/ios/advanced_topics/linker/

And comments from Xamarin about this issue:

https://bugzilla.xamarin.com/show_bug.cgi?id=52672#c12
https://bugzilla.xamarin.com/show_bug.cgi?id=52672#c14

**Comment by mikkeljohnsen** [comment] 2017-03-16 10:21
@xplicit Will you fix it so you dot't have to make these linker settings.

I still don't know how to get it to work. What exactly should I do. I tried "--nolinkaway" with no luck. ?

**Comment by xplicit** [comment] 2017-03-16 11:55
@mikkeljohnsen do you get `ArgumentException` if set `-nolink` option? If you still get it, can you create small solution which reproduces the issue?

![Link options](https://developer.xamarin.com/guides/ios/advanced_topics/linker/Images/Image1.png)

If you don't get exception with `-nolink` option, you can try to add at main project startup:

    var req = (HttpWebRequest)WebRequest.Create("http://sample.com");
    req.UserAgent = "preserve property";

This should preserve `UserAgent` property from removing by linker.

It will work without additional linker settings, when Net Standard 2.0 will out. Net Standard 2.0 have got support of `HttpWebRequest.UserAgent` property, which is missing in previous versions of API. Unfortunately, we can't control how Xamarin implements system libraries and how their linker works. What we can do is to try workaround such bugs (because I'm pretty sure this is Xamarin implementation bug: we can't modify header due to error saying that we have to use `UserAgent` property, but property does not exist in API and even if we try to get property through reflection it does not guarantee that it does not removed by Xamarin linker and we have no ways to say linker from library to keep the property.

**Comment by xplicit** [comment] 2017-03-17 01:34
@mikkeljohnsen And can you check your project with version [1.0.38](https://www.nuget.org/packages/ServiceStack.Client.Core/1.0.38)?

**Comment by mikkeljohnsen** [comment] 2017-03-17 10:22
I just reverted back to PCL in wait for .NEtStandard 2.0.

But I will try soon.

**Comment by mikkeljohnsen** [comment] 2017-03-20 07:29
1.0.38 seems to have fixed the User-Agent problem. But now I get:

```
The type initializer for 'ServiceStack.Text.Json.JsonReader`1' threw an exception.
  at ServiceStack.Text.Json.JsonReader.GetParseFn (System.Type type) [0x00079] in <1ef30afc83a44928ac1578d9a13696e5>:0 
  at ServiceStack.Text.JsonSerializer.DeserializeFromString (System.String value, System.Type type) [0x00008] in <1ef30afc83a44928ac1578d9a13696e5>:0 
  at ServiceStack.Text.JsonSerializer.DeserializeFromStream (System.Type type, System.IO.Stream stream) [0x00012] in <1ef30afc83a44928ac1578d9a13696e5>:0 
  at ServiceStack.ServiceClientBase.AsyncDeserializeFromStream (System.Type type, System.IO.Stream fromStream) [0x00006] in <801954c37ff74a688a1163ce6e7f429c>:0 
  at ServiceStack.AsyncServiceClient+<>c__DisplayClass141_0`1[T].<ReadCallBack>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x00184] in <801954c37ff74a688a1163ce6e7f429c>:0 
```

Do I need to call "NetStandardPclExportClient.Configure ();:" ?
It do not seems to make any difference for the above error.

**Comment by mikkeljohnsen** [comment] 2017-03-21 15:05
I tried this. But it is not working either.

```
<?xml version="1.0" encoding="utf-8"?>
<linker>
	<assembly fullname="ServiceStack.Text">
		<type fullname="ServiceStack.Text.Json.JsonReader`1">
			<method name="GetParseFn" />
		</type>
		<type fullname="ServiceStack.Text.Common.DeserializeListWithElements`2">
			<method name="ParseGenericList" />
		</type>
		<type fullname="ServiceStack.Text.Common.WriteListsOfElements`2">
			<method name="WriteList" />
			<method name="WriteArray" />
		</type>
	</assembly>
</linker>
```

I give up on ServiceStack.Client.Core and .NETStandard. For now.
