### ISSUE TITLE
ORMLite Oracle (4.0.43) Breaking changes

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#337] opened 2015-08-21 20:45 UTC
Hello,

The ORMLite Oracle Provider is now breaking existing functionality, please see this repo for details.

https://github.com/stephenpatten/SSORM4.0.43OracleRepo

Basically the provider now thinks that bools are varchars. Look in the models folder for a before and after DDL.

Thanks Demis.

**Comment by mythz** [comment] 2015-08-21 21:41
I know Oracle has failing tests, I've been in contact with the previous maintainers but none of them currently have the time or resources to fix the outstanding issues. I've done as much as I can without having an Oracle instance to run it on, but any further fixes need to be resolved by an Oracle user.

The repro isn't useful as no-one without access to Oracle can run them (inc. me), for any repro's to be useful they'll needed to be added to the main OrmLite test project so they're available to the previous maintainers. But it's likely this is already covered by some of the existing failing tests.

I'm currently holding up this release for an additional 1-2 weeks to see if the existing maintainers can come forward to resolve them, if they don't I may have to drop distributing Oracle and the other unsupported Firebird and VistaDB RDBMS's entirely - none of them are worth the resources to maintain and are currently hurting progress of the OrmLite's projects supported RDBMS's.

**Closed by mythz** 2015-08-21 21:41 UTC

**Comment by stephenpatten** [comment] 2015-08-21 22:06
That's not what I wanted to here, we're in stage/production right now and our whole application just failed. 

I've read this months check-ins and no one has really made substantial changes to the Oracle Provider but you refactored a bunch of stuff in ORMLite and the Sql server provider had a lot of attention, dang it, 43 was going to be the one we released with and I could put this in maintenance. 

Should I just use ORMLite 4.0.42 and bump everything else to 4.0.43? There are great changes in 43 for Redis and what not that I have to have to go into production... ideas?

**Comment by mythz** [comment] 2015-08-21 22:25
I'd revert to v4.0.42 and wouldn't upgrade. Different versions aren't expected to work together, it may work as I don't recall a change to SS.Interfaces that OrmLite relies on, but it's not tested or supported.

I've contacted the previous maintainers ~2 weeks ago, they were able to run it and report there were a number of failed tests but they've also said no-one from the team have the time to work on it. One of them may try put aside some of their own time on the weekends within the next 1-2 weeks but wasn't able to commit. The Oracle provider's future is currently uncertain, I'll wait 1-2 weeks to decide whether to continue distributing it or not.

**Comment by stephenpatten** [comment] 2015-08-21 22:38
Really sorry you're in this predicament.. and as always I appreciate your candor and your hard work. I have time this weekend to mess with it, if you would just answer your gmail if I have questions. Any advice on setting this up quickly to replicate the failing tests?

**Comment by mythz** [comment] 2015-08-21 22:44
It should be easy to resolve even from the v4.0.43 binaries. e.g. If the issue is with bools, you can register a custom converter and debug what works:

```csharp
OracleDialect.Provider.RegisterConverter<bool>(new CustomBoolConverter());

public class CustomBoolConverter : OracleBoolConverter 
{
        public override string ToQuotedString(Type fieldType, object value) {
            return base.ToQuotedString(fieldType, value);
        }
        public override void InitDbParam(IDbDataParameter p, Type fieldType) {
            return base.InitDbParam(p, fieldType);
        }
        public override object ToDbValue(Type fieldType, object value) { 
            return base.ToDbValue(fieldType, value);
        }
        public override object FromDbValue(Type fieldType, object value) {
            return base.FromDbValue(fieldType, value);
        }
}
```

Basically just overriding the different [Converter API's](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite/IOrmLiteConverter.cs#L30) and put breakpoints to see where the issue might be.

**Comment by mythz** [comment] 2015-08-21 23:03
Yep happy to be on call on gmail while you're debugging it and help where I can.

**Comment by stephenpatten** [comment] 2015-08-21 23:49
This is why I moved to 4.0.43

System.TypeLoadException: Could not load type 'ServiceStack.OrmLite.ParameterizedSqlExpression`1' from assembly 'ServiceStack.OrmLite, Version=4.0.42.0, Culture=neutral, PublicKeyToken=null'.
   at ServiceStack.OrmLite.Oracle.OracleOrmLiteDialectProvider.SqlExpression[T]()
   at ServiceStack.OrmLite.WriteExpressionCommandExtensions.Update[T](IDbCommand dbCmd, Object updateOnly, Expression`1 where)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
   at NeustarApp.ServiceInterface.DataAccess.Repository.Update(Lead model)
