### ISSUE TITLE
System.IO.FileNotFoundException with 4.0.32

### ISSUE THREAD

**Issue by ericpeterson87** [ServiceStack/Issues#166] opened 2014-10-24 16:27 UTC
when i build and use Smart Assembly on a project that has been working fine until i updated to 4.0.30+ (currently on 4.0.32), i am getting the following error on all machines EXCEPT my development machine:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
```
i have tried referencing system.net in the project as well (i only have v4 on my dev machine).

if i copy the release build of the UN-obfuscated binaries to my test system things work as expected. This sounds eerily similar to what we had to monkey with in a past issue.

any ideas?

**Comment by systemsymbiosis** [comment] 2015-08-04 11:55
I observe this same issue in Sitefinity 8.1

Here is the exception/binding error

Could not load file or assembly 'System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' could not be loaded.

=== Pre-bind state information === LOG: DisplayName = System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes (Fully-specified) LOG: Appbase = file:///C:/Dev/EC/DEV/SitefinityWebApp/ LOG: Initial PrivatePath = C:\Dev\EC\DEV\SitefinityWebApp\bin Calling assembly : ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43. === LOG: This bind starts in default load context. LOG: Using application configuration file: C:\Dev\EC\DEV\SitefinityWebApp\web.config LOG: Using host configuration file: C:\Program Files\IIS Express\config\templates\PersonalWebServer\aspnet.config LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config. LOG: Redirect found in application configuration file: 2.0.5.0 redirected to 5.0.5.0. LOG: Post-policy reference: System.Net, Version=5.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e LOG: The same bind was seen before, and was failed with hr = 0x80070002.

I have installed the following Nuget package to see if it fixes assembly resolution for System.Net

https://www.nuget.org/packages/Microsoft.NETCore.Platforms/

The above package did not help.

My web.config has a binding redirect as follows
```xml
      <dependentAssembly>
        <assemblyIdentity name="System.Net" publicKeyToken="7cec85d7bea7798e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.5.0" newVersion="5.0.5.0" />
      </dependentAssembly>
```
I tried settting this to
```xml
      <dependentAssembly>
        <assemblyIdentity name="System.Net" publicKeyToken="7cec85d7bea7798e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.5.0" newVersion="4.0.0.0" />
      </dependentAssembly>
```
And I added a assembly reference to my SitefinityWebApp project to System.Net. I also tried setting copy local to true.

I also tried installing the patch and it was also blocked on install with a message stating:

KB2468871v2 does not apply, or is blocked by another condition on your computer.

None of my ideas are working.

**Comment by mythz** [comment] 2015-08-04 17:09
This sounds like the [PCL System.Net Issue](https://github.com/ServiceStack/ServiceStack/blob/master/docs/2014/release-notes.md#upgrade-all-servicestack-nuget-packages)

The https://www.nuget.org/packages/Microsoft.NETCore.Platforms/ looks like it's only for .NET Core projects? in which case that wont help.

Have you tried explicitly referencing 4.0.0.0 of System.Net from the GAC, i.e:

![pcl-system net](https://cloud.githubusercontent.com/assets/89361/9067189/93786b26-3b0e-11e5-8dfe-ab78e82f4621.png)

**Comment by systemsymbiosis** [comment] 2015-08-04 21:35
Thanks for the reply, yes I tried the explicit reference and when that did not work I also tried setting copy local to true so that System.Net was in the bin directory and 100% should have been found via the probing. Totally weird issue. I think my only option at this stage maybe to roll back to an earlier version. I'll raise a support ticket with Telerik and see what they say.

**Comment by systemsymbiosis** [comment] 2015-08-12 00:56
Telerik support came up with a solution for this issue. I post here in case anyone comes across this issue in future.

Hi Austin,

Thank you for contacting us.

I have not been able to find other people reporting the same problem, however the problem seems to be coming from your binding redirect. By default you should not have a binding redirect for System.Net. Have you tried without any binding redirect? I have investigated this on my local projects and none of them have such binding redirects. Furthermore I was able to reproduce the issue when adding the binding redirect you have in your web.config after the change. It seems that you should not be targeting the versions before 2.0.5.0 but those after that. I have modified the binding redirect in the following way and it is working on my end. Can you please try removing it completely and change it with the one below and let me know the results?

<dependentAssembly>
  <assemblyIdentity name="System.Net" publicKeyToken="7cec85d7bea7798e" culture="neutral" />
  <bindingRedirect oldVersion="2.0.5.1-4.0.0.0" newVersion="4.0.0.0" />
</dependentAssembly>

I hope the above information helps. Please do not hesitate to get back to me if you need further assistance on this matter.

Regards,
Velizar Bishurov
Telerik

**Comment by mythz** [comment] 2015-08-12 03:09
@systemsymbiosis Awesome thanks for the info, could be invaluable for others experiencing the same issue.

**Comment by mythz** [comment] 2015-10-01 03:38
Going to close this, it appears to be due to PCL dlls and external framework version patches with Smart Assembly which we don't have control over in the ServiceStack .dlls. 

I'll point back anyone to this thread if they have a similar issue although as It's been almost a year this may have been resolved in a recent version of Smart Assembly or .NET Framework update.

**Closed by mythz** 2015-10-01 03:38 UTC
